stages:
  - test
  - build
  - deploy
variables:
  password: 'Mw!HGrF5)p#z^G.'
  username: 'jobugua97@gmail.com'

build_app:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - cd upload
    - docker build -t lipa_backend .
    - docker login -u $username -p $password
    - docker tag  lipa_backend:latest mbuguanganga/lipa_backend:latest
    - docker push mbuguanganga/lipa_backend:latest
  only:
    - Deployment

deploy_app:
  image: ubuntu
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - chmod 600 upload/id_rsa
    - ssh-add upload/id_rsa
    - ssh -o StrictHostKeyChecking=no ubuntu@100.25.166.226 "cd lipa_backend/upload && docker login -u 'jobugua97@gmail.com' -p 'Mw!HGrF5)p#z^G.' &&git pull && docker-compose pull && docker-compose up -d --build "
  only:
    - Deployment